---
exclude_paths:
  - db/migrate
detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    exclude:
      - V1
  UncommunicativeVariableName:
    exclude:
      - e
  NilCheck:
    exclude:
      - V1::AuthenticateInteractor#resolve
      - V1::Users::CreateInteractor#create
  InstanceVariableAssumption:
    exclude:
      - ApplicationController
  FeatureEnvy:
    exclude:
      - Api::V1::UsersController#json_response
      - Api::V1::TimelinesController#json_response
      - Api::V1::StoriesController#json_response
  TooManyInstanceVariables:
    max_instance_variables: 7