require: rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - Gemfile
    - bin/*
Rails:
  Enabled: true
Rails/FilePath:
  Exclude:
    - config/environments/development.rb
Style/Documentation:
    Enabled: false
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/AbcSize:
  Max: 17
